apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-5803"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-5803"
  template:
    metadata:
      labels:
        app: "myakscluster-5803"
    spec:
      containers:
        - name: "myakscluster-5803"
          image: "acrmarcioteixeira.azurecr.io/myakscluster"
          ports:
          - containerPort: 8080