apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-b85a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-b85a"
  template:
    metadata:
      labels:
        app: "myakscluster-b85a"
    spec:
      containers:
        - name: "myakscluster-b85a"
          image: "acrmarcioteixeira.azurecr.io/myakscluster"
          ports:
          - containerPort: 8080