name: CI-CD

on: [ "main" ]
jobs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: autenticando o usuário
      uses: azure/docker-login@v1
      with:
        login-server: acrmarcioteixeira.azurecr.io
        username: ${{ secrets.acr_acrmarcioteixeira_username }}
        password: ${{ secrets.acr_acrmarcioteixeira_password }}
    
    - name: construindo a imagem e enviando para o ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src" -f  "src/dockerfile" -t acrmarcioteixeira.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=src/dockerfile
        docker push acrmarcioteixeira.azurecr.io/myakscluster:${{ github.sha }}
      tags: |
         acrmarcioteixeira.azurecr.io/kube-news:latest
         acrmarcioteixeira.azurecr.io/kube-news:${{github.run_number}}
   
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep appKubnews | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace appKubnews`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: appKubnews
        container-registry-url: acrmarcioteixeira.azurecr.io
        container-registry-username: ${{ secrets.acr_acrmarcioteixeira_username }}
        container-registry-password: ${{ secrets.acr_acrmarcioteixeira_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: appKubnews
        manifests: |
          k8s/deployment.yaml
        images: |
          acrmarcioteixeira.azurecr.io/kube-news:${{ github.sha }}
        imagepullsecrets: |
          kubnewsdockerauth
