name: CI-CD
on: [push]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrmarcioteixeira.azurecr.io
        username: ${{ secrets.acr_acrmarcioteixeira_username }}
        password: ${{ secrets.acr_acrmarcioteixeira_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src" -f  "src/dockerfile" -t acrmarcioteixeira.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=src/dockerfile
        docker push acrmarcioteixeira.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep app-kube-news | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace app-kube-news`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: app-kube-news
        container-registry-url: acrmarcioteixeira.azurecr.io
        container-registry-username: ${{ secrets.acr_acrmarcioteixeira_username }}
        container-registry-password: ${{ secrets.acr_acrmarcioteixeira_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: app-kube-news
        manifests: |
          k8s/deployment.yaml
        images: |
          acrmarcioteixeira.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
